openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: Your API Description
servers:
  - url: http://localhost:3000
    description: Development server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: string
          example: "123"
        name:
          type: string
          example: "John Doe"
        position:
          type: string
          example: "Software Engineer"
        department:
          type: string
          example: "Engineering"
paths:
  /employees:
    get:
      security:
        - bearerAuth: []
      tags:
        - Employee Controller
      summary: Get All Employees
      responses:
        200:
          description: Fetched Successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Error
