openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
components:
  schemas:
    AuthRequest:
      type: object
      properties:
        user:
          type: string
        pwd:
          type: string
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
paths:
  /auth:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: string
                  example: "walt2"
                pwd:
                  type: string
                  example: "Aa$12345"
      responses:
        "200":
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySW5mbyI6eyJ1c2VybmFtZSI6IndhbHQyIiwicm9sZXMiOlsyMDAxLDE5ODRdfSwiaWF0IjoxNzIxNjA2MjE2LCJleHAiOjE3MjE2MDYyNzZ9.7E-C0xJhOg58Or8QeisGVqedhXEfNVpZUm3gD9EUSsE"
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
